package main

type Poloniex struct {
	BTC1CR struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_1CR"`
	BTCABY struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_ABY"`
	BTCADN struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_ADN"`
	BTCAMP struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_AMP"`
	BTCBBR struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_BBR"`
	BTCBCN struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_BCN"`
	BTCBCY struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_BCY"`
	BTCBELA struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_BELA"`
	BTCBITCNY struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_BITCNY"`
	BTCBITS struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_BITS"`
	BTCBITUSD struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_BITUSD"`
	BTCBLK struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_BLK"`
	BTCBLOCK struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_BLOCK"`
	BTCBTCD struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_BTCD"`
	BTCBTM struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_BTM"`
	BTCBTS struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_BTS"`
	BTCBURST struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_BURST"`
	BTCC2 struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_C2"`
	BTCCGA struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_CGA"`
	BTCCLAM struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_CLAM"`
	BTCCNMT struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_CNMT"`
	BTCCURE struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_CURE"`
	BTCDAO struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_DAO"`
	BTCDASH struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_DASH"`
	BTCDCR struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_DCR"`
	BTCDGB struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_DGB"`
	BTCDIEM struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_DIEM"`
	BTCDOGE struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_DOGE"`
	BTCEMC2 struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_EMC2"`
	BTCETH struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_ETH"`
	BTCEXP struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_EXP"`
	BTCFCT struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_FCT"`
	BTCFIBRE struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_FIBRE"`
	BTCFLDC struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_FLDC"`
	BTCFLO struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_FLO"`
	BTCFLT struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_FLT"`
	BTCGAME struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_GAME"`
	BTCGAP struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_GAP"`
	BTCGEO struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_GEO"`
	BTCGRC struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_GRC"`
	BTCGRS struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_GRS"`
	BTCHUC struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_HUC"`
	BTCHYP struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_HYP"`
	BTCHZ struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_HZ"`
	BTCIOC struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_IOC"`
	BTCLQD struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_LQD"`
	BTCLSK struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_LSK"`
	BTCLTBC struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_LTBC"`
	BTCLTC struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_LTC"`
	BTCMAID struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_MAID"`
	BTCMCN struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_MCN"`
	BTCMINT struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_MINT"`
	BTCMMC struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_MMC"`
	BTCMMNXT struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_MMNXT"`
	BTCMYR struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_MYR"`
	BTCNAUT struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_NAUT"`
	BTCNAV struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_NAV"`
	BTCNBT struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_NBT"`
	BTCNEOS struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_NEOS"`
	BTCNMC struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_NMC"`
	BTCNOBL struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_NOBL"`
	BTCNOTE struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_NOTE"`
	BTCNSR struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_NSR"`
	BTCNXT struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_NXT"`
	BTCOMNI struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_OMNI"`
	BTCPIGGY struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_PIGGY"`
	BTCPINK struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_PINK"`
	BTCPOT struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_POT"`
	BTCPPC struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_PPC"`
	BTCPTS struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_PTS"`
	BTCQBK struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_QBK"`
	BTCQORA struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_QORA"`
	BTCQTL struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_QTL"`
	BTCRADS struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_RADS"`
	BTCRBY struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_RBY"`
	BTCRDD struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_RDD"`
	BTCRIC struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_RIC"`
	BTCSC struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_SC"`
	BTCSDC struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_SDC"`
	BTCSILK struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_SILK"`
	BTCSJCX struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_SJCX"`
	BTCSTR struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_STR"`
	BTCSWARM struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_SWARM"`
	BTCSYNC struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_SYNC"`
	BTCSYS struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_SYS"`
	BTCUNITY struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_UNITY"`
	BTCVIA struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_VIA"`
	BTCVOX struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_VOX"`
	BTCVRC struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_VRC"`
	BTCVTC struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_VTC"`
	BTCWDC struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_WDC"`
	BTCXBC struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_XBC"`
	BTCXC struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_XC"`
	BTCXCN struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_XCN"`
	BTCXCP struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_XCP"`
	BTCXCR struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_XCR"`
	BTCXDN struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_XDN"`
	BTCXEM struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_XEM"`
	BTCXMG struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_XMG"`
	BTCXMR struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_XMR"`
	BTCXPB struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_XPB"`
	BTCXPM struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_XPM"`
	BTCXRP struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_XRP"`
	BTCXST struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_XST"`
	BTCXUSD struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_XUSD"`
	BTCXVC struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_XVC"`
	BTCYACC struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"BTC_YACC"`
	ETHDAO struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"ETH_DAO"`
	ETHLSK struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"ETH_LSK"`
	USDTBTC struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"USDT_BTC"`
	USDTDASH struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"USDT_DASH"`
	USDTETH struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"USDT_ETH"`
	USDTLTC struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"USDT_LTC"`
	USDTNXT struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"USDT_NXT"`
	USDTSTR struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"USDT_STR"`
	USDTXMR struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"USDT_XMR"`
	USDTXRP struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"USDT_XRP"`
	XMRBBR struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"XMR_BBR"`
	XMRBCN struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"XMR_BCN"`
	XMRBLK struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"XMR_BLK"`
	XMRBTCD struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"XMR_BTCD"`
	XMRDASH struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"XMR_DASH"`
	XMRDIEM struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"XMR_DIEM"`
	XMRDSH struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"XMR_DSH"`
	XMRHYP struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"XMR_HYP"`
	XMRIFC struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"XMR_IFC"`
	XMRLTC struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"XMR_LTC"`
	XMRMAID struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"XMR_MAID"`
	XMRMNTA struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"XMR_MNTA"`
	XMRNXT struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"XMR_NXT"`
	XMRQORA struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"XMR_QORA"`
	XMRXDN struct {
		BaseVolume    string `json:"baseVolume"`
		High24hr      string `json:"high24hr"`
		HighestBid    string `json:"highestBid"`
		ID            int    `json:"id"`
		IsFrozen      string `json:"isFrozen"`
		Last          string `json:"last"`
		Low24hr       string `json:"low24hr"`
		LowestAsk     string `json:"lowestAsk"`
		PercentChange string `json:"percentChange"`
		QuoteVolume   string `json:"quoteVolume"`
	} `json:"XMR_XDN"`
}
